build: false
shallow_clone: true
platform:
  - x64
clone_folder: C:\projects\joomla-cms
## Build matrix for lowest and highest possible targets
environment:
  matrix:
  - php_ver_target: 5.6
  - php_ver_target: 7.0
  - php_ver_target: 7.1

init:
  - SET PATH=C:\Program Files\OpenSSL;C:\tools\php;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET PHP=1
  - SET ANSICON=121x90 (121x90)
services:
  - mssql2014
  - mysql
  - postgresql94
  - iis

## Install PHP and composer, and run the appropriate composer command
install:
    - IF EXIST C:\tools\php (SET PHP=0)
    - ps: >-
        If ($env:php_ver_target -eq "5.6") {
        appveyor-retry cinst --ignore-checksums -y --forcex86 php --version ((choco search php --exact --all-versions -r | select-string -pattern $Env:php_ver_target | Select-Object -first 1) -replace '[php|]','')
        } Else {
        appveyor-retry cinst --ignore-checksums -y php --version ((choco search php --exact --all-versions -r | select-string -pattern $Env:php_ver_target | Select-Object -first 1) -replace '[php|]','')}
    - cinst -y sqlite
    - cd C:\tools\php
    - ps: >-
        If ($env:php_ver_target -eq "5.6") {
          If ($env:PHP -eq "1") {
            appveyor DownloadFile https://files.nette.org/misc/php-sqlsrv.zip
            7z x php-sqlsrv.zip > $null
            copy SQLSRV\php_sqlsrv_56_nts.dll ext\php_sqlsrv_nts.dll
            copy SQLSRV\php_pdo_sqlsrv_56_nts.dll ext\php_pdo_sqlsrv_nts.dll
            Remove-Item C:\tools\php\* -include .zip}}
    - ps: >-
        If ($env:php_ver_target -eq "7.0") {
          If ($env:PHP -eq "1") {
            appveyor DownloadFile https://github.com/Microsoft/msphpsql/releases/download/4.1.5-Windows/7.0.zip
            7z x 7.0.zip > $null
            copy 7.0\x64\php_pdo_sqlsrv_7_nts.dll ext\php_pdo_sqlsrv_nts.dll
            copy 7.0\x64\php_sqlsrv_7_nts.dll ext\php_sqlsrv_nts.dll
            Remove-Item C:\tools\php\* -include .zip}}
    - ps: >-
        If ($env:php_ver_target -eq "7.1") {
          If ($env:PHP -eq "1") {
            appveyor DownloadFile https://github.com/Microsoft/msphpsql/releases/download/4.1.5-Windows/7.1.zip
            7z x 7.1.zip > $null
            copy 7.1\x64\php_pdo_sqlsrv_71_nts.dll ext\php_pdo_sqlsrv_nts.dll
            copy 7.1\x64\php_sqlsrv_71_nts.dll ext\php_sqlsrv_nts.dll
            Remove-Item C:\tools\php\* -include .zip}}
    - IF %PHP%==1 copy php.ini-production php.ini /Y
    - IF %PHP%==1 echo date.timezone="UTC" >> php.ini
    - IF %PHP%==1 echo extension_dir=ext >> php.ini
    - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
    - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
    - IF %PHP%==1 echo extension=php_fileinfo.dll >> php.ini
    - IF %PHP%==1 echo extension=php_gd2.dll >> php.ini
    - IF %PHP%==1 echo extension=php_pdo_mysql.dll >> php.ini
    - IF %PHP%==1 echo extension=php_pdo_sqlsrv_nts.dll >> php.ini
    - IF %PHP%==1 echo extension=php_sqlsrv_nts.dll >> php.ini
    - IF %PHP%==1 echo extension=php_pdo_pgsql.dll >> php.ini
    - IF %PHP%==1 echo extension=php_pdo_sqlite.dll >> php.ini
    - IF %PHP%==1 echo extension=php_sqlite3.dll >> php.ini
    - IF %PHP%==1 echo extension=php_mysqli.dll >> php.ini
    - IF %PHP%==1 echo extension=php_pgsql.dll >> php.ini
    - IF %PHP_VER_TARGET%==5.6 IF %PHP%==1 echo extension=php_mysql.dll >> php.ini
    - ps: >-
        If ($env:php_ver_target -eq "5.6") {
          If ($env:PHP -eq "1") {
            appveyor DownloadFile http://windows.php.net/downloads/pecl/releases/wincache/1.3.7.12/php_wincache-1.3.7.12-5.6-nts-vc11-x86.zip
            7z x php_wincache-1.3.7.12-5.6-nts-vc11-x86.zip > $null
            copy php_wincache.dll ext\php_wincache.dll
            Remove-Item C:\tools\php\* -include .zip}}
    - ps: >-
        If ($env:php_ver_target -eq "7.0") {
          If ($env:PHP -eq "1") {
            appveyor DownloadFile http://windows.php.net/downloads/pecl/releases/wincache/2.0.0.8/php_wincache-2.0.0.8-7.0-nts-vc14-x64.zip
            7z x php_wincache-2.0.0.8-7.0-nts-vc14-x64.zip > $null
            copy php_wincache.dll ext\php_wincache.dll
            Remove-Item C:\tools\php\* -include .zip
            echo extension=php_wincache.dll >> php.ini}}
    - ps: >-
        If ($env:php_ver_target -eq "7.1") {
          If ($env:PHP -eq "1") {
            appveyor DownloadFile http://windows.php.net/downloads/pecl/releases/wincache/2.0.0.8/php_wincache-2.0.0.8-7.1-nts-vc14-x64.zip
            7z x php_wincache-2.0.0.8-7.1-nts-vc14-x64.zip > $null
            copy php_wincache.dll ext\php_wincache.dll
            Remove-Item C:\tools\php\* -include .zip
            echo extension=php_wincache.dll >> php.ini}}
    - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
    - appveyor-retry appveyor DownloadFile https://getcomposer.org/composer.phar
    - cd C:\projects\joomla-cms
    - appveyor-retry composer install --no-progress --profile

before_test:
#  Database setup for MySQL via PowerShell tools
  - >
    "C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" -u root -p"Password12!" -e "CREATE DATABASE IF NOT EXISTS joomla_ut;"
  - >
    "C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" -u root -p"Password12!" joomla_ut < tests\unit\schema\mysql.sql

#  Database setup for PostgreSQL
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\9.4\bin\;%PATH%
  - createdb joomla_ut
  - psql -d joomla_ut -a -f tests\unit\schema\postgresql.sql

# Database setup for SQL Server
  - ps: $sqlInstance = "(local)\SQL2014"
  - ps: sqlcmd -b -E -S "$sqlInstance" -Q "CREATE DATABASE joomla_ut"
  - ps: sqlcmd -S "$sqlInstance" -U "sa" -P "Password12!" -i $env:APPVEYOR_BUILD_FOLDER\tests\unit\schema\sqlsrv.sql

test_script:
  - cd C:\projects\joomla-cms
  - libraries/vendor/bin/phpunit -c appveyor-phpunit.xml
