image: Visual Studio 2022
build: false
platform:
  - x64
clone_folder: C:\projects\joomla-cms

## Build matrix for lowest and highest possible targets
environment:
  PHPBuild: "x64"
  matrix:
  - php_ver_target: 7.2
  - php_ver_target: 7.3
  - php_ver_target: 7.4
  - php_ver_target: 8.0
  - php_ver_target: 8.1

matrix:
  allow_failures:
    - php_ver_target: 8.1

init:
  - SET PATH=C:\Tools\php;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET ANSICON=121x90 (121x90)
services:
  - mysql
  - iis

## Install PHP and composer, and run the appropriate composer command
install:
    - ps: >-
        appveyor-retry choco install --no-progress --params '""/InstallDir:C:\tools\php""' --ignore-checksums -y php --version ((choco search php --exact --all-versions -r | select-string -pattern $env:php_ver_target | sort { [version]($_ -split '\|' | select -last 1) } -Descending | Select-Object -first 1) -replace '[php|]','')
    - cd C:\tools\php
    - copy php.ini-production php.ini /Y
    - echo date.timezone="UTC" >> php.ini
    - echo extension_dir=ext >> php.ini
    - echo extension=php_openssl.dll >> php.ini
    - echo extension=php_mbstring.dll >> php.ini
    - echo extension=php_fileinfo.dll >> php.ini
    - IF %php_ver_target% LSS 8 echo extension=php_gd2.dll >> php.ini
    - IF %php_ver_target% GEQ 8 echo extension=gd >> php.ini
    - echo extension=php_gmp.dll >> php.ini
    - echo extension=php_pgsql.dll >> php.ini
    - echo extension=php_pdo_pgsql.dll >> php.ini
    - echo extension=php_pdo_mysql.dll >> php.ini
    - echo extension=php_mysqli.dll >> php.ini
    - echo extension=php_curl.dll >> php.ini
    - echo zend_extension=php_opcache.dll >> php.ini
    - echo opcache.enable_cli=1 >> php.ini
    - echo extension=php_ldap.dll >> php.ini
    - choco install composer
    - cd C:\projects\joomla-cms
    - refreshenv
    - composer install --no-progress --profile
before_test:
#  Database setup for MySQL via PowerShell tools
  - >
    "C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" -u root -p"Password12!" -e "CREATE DATABASE IF NOT EXISTS test_joomla;"

test_script:
  - cd C:\projects\joomla-cms
  - libraries/vendor/bin/phpunit --testsuite Unit
  - libraries/vendor/bin/phpunit --testsuite Integration  --configuration tests/phpunit-appveyor.xml.dist
