# Forces new Travis-CI Infrastructure
sudo: false

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

services:
  - memcached
  - redis-server

before_script:
  # Make sure all dev dependencies are installed
  - composer install
  # Set up databases for testing
  - mysql -e 'create database joomla_ut;'
  - mysql joomla_ut < tests/unit/schema/mysql.sql
  - psql -c 'create database joomla_ut;' -U postgres
  - psql -d joomla_ut -a -f tests/unit/schema/postgresql.sql
  # Set up Apache
  # - ./build/travis/php-apache.sh
  # Enable additional PHP extensions
  - if [ $TRAVIS_PHP_VERSION != "7.0" ]; then phpenv config-add build/travis/phpenv/memcached.ini; fi
  # PHP 5.3 and 5.4 use APC
  - if [ $TRAVIS_PHP_VERSION == "5.3" ] || [ $TRAVIS_PHP_VERSION == "5.4" ]; then phpenv config-add build/travis/phpenv/apc-$TRAVIS_PHP_VERSION.ini; fi
  # PHP 5.5+ use APCu
  - if [ $TRAVIS_PHP_VERSION == "5.5" ] || [ $TRAVIS_PHP_VERSION == "5.6" ]; then printf "\n" | pecl install apcu-beta; fi
  - if [ $TRAVIS_PHP_VERSION != "7.0" ]; then phpenv config-add build/travis/phpenv/redis.ini; fi

script:
  - libraries/vendor/bin/phpunit --configuration travisci-phpunit.xml
  - if [ $TRAVIS_PHP_VERSION != "7.0" ]; then libraries/vendor/bin/phpcs --report=full --extensions=php -p --standard=build/phpcs/Joomla .; fi

branches:
  except:
    - 2.5.x
