# Forces new Travis-CI Infrastructure
sudo: false

language: php

env:
  global:
    - RUN_UNIT_TESTS="yes"
    - INSTALL_APCU="yes"
    - INSTALL_MEMCACHED="yes"
    - INSTALL_REDIS="yes"

matrix:
  fast_finish: true
  include:
    # Requires older Precise image
    - php: 5.3
      env:
        - INSTALL_APC="yes"
        - INSTALL_APCU="no"
        - INSTALL_MEMCACHE="yes"
      sudo: true
      dist: precise
    # The new Trusty image has issues with running APC, do not enable it here
    - php: 5.4
      env:
        - INSTALL_APCU="no"
        - INSTALL_MEMCACHE="yes"
      dist: trusty
    - php: 5.5
      env:
        - INSTALL_MEMCACHE="yes"
      dist: trusty
    - php: 5.6
      env:
        - INSTALL_MEMCACHE="yes"
      dist: trusty
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4snapshot
    - php: nightly
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

services:
  - memcache
  - memcached
  - redis-server
  - mysql
  - postgresql

before_script:
  # Make sure all dev dependencies are installed
  - if [[ $RUN_UNIT_TESTS == "yes" ]]; then bash build/travis/unit-tests.sh $PWD; fi

script:
  - if [[ $RUN_UNIT_TESTS == "yes" ]]; then libraries/vendor/bin/phpunit --configuration travisci-phpunit.xml; fi

branches:
  except:
    - 2.5.x
