language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

services:
  - memcached
  - redis-server

before_script:
  - composer self-update
  - pyrus install -f pear/PHP_CodeSniffer-1.5.4
  - pyrus install -f pear/Cache_Lite
  - phpenv rehash
  - mysql -e 'create database joomla_ut;'
  - mysql joomla_ut < tests/unit/suites/database/stubs/mysql.sql
  - psql -c 'create database joomla_ut;' -U postgres
  - psql -d joomla_ut -a -f tests/unit/suites/database/stubs/postgresql.sql
  - phpenv config-add build/travis/phpenv/memcached.ini
  - phpenv config-add build/travis/phpenv/apc-$TRAVIS_PHP_VERSION.ini
  - phpenv config-add build/travis/phpenv/redis.ini

script:
  - phpunit --configuration travisci-phpunit.xml
  - phpcs --report=full --extensions=php -p --standard=build/phpcs/Joomla .

branches:
  except:
    - 2.5.x

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/18687d008d633d02aa84
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

