#### Browser Version is used for automatically prefixing the stylesheets.
#### IMPORTANT: Joomla 4 only supports the latest version of each browser!
Browsers:
    'last 1 version'

vendors:
#### PLEASE ONLY ALTER THE VERSION NUMBERS BELLOW. USE x.x.x NOT LATEST! ###
    'jquery':
                 'version': '3.2.1'
                 'dependencies': ''

    'jquery-migrate':
                  'version': '1.4.1'
                  'dependencies': 'jquery'
    'bootstrap':
                  'version': '4.0.0-beta.2'
                  'dependencies': 'jquery'
    'font-awesome':
                  'version': '4.7.0'
                  'dependencies': ''
    '@claviska/jquery-minicolors':
                  'version': '2.2.6'
                  'dependencies': 'jquery'
    'jquery-sortable':
                  'version': '0.9.13'
                  'dependencies': 'jquery'
    'jquery-ui':
                  'version': '1.12.1'
                  'dependencies': 'jquery'
    'mediaelement':
                  'version': '4.2.7'
                  'dependencies': ''
    'punycode':
                  'version': '1.4.1'
                  'dependencies': ''
    'tinymce':
                  'version': '4.7.4'
                  'dependencies': ''
    'awesomplete':
                  'version': '1.1.2'
                  'dependencies': ''
    'dragula':
                  'version': '3.7.2'
                  'dependencies': ''
    'codemirror':
                  'version': '5.32.0'
                  'dependencies': ''
    'cropperjs':
                  'version': '1.1.3'
                  'dependencies': ''
    'flying-focus-a11y':
                  'version': '1.5.5'
                  'dependencies': ''
    'diff':
                  'version': '3.4.0'
                  'dependencies': ''
    'wicked-good-xpath':
                  'version': '1.3.0'
                  'dependencies': ''
    'joomla-ui-custom-elements':
                  'version': '0.0.9'
                  'dependencies': ''

webcomponents:
          'field-media':
                'css': 'media/system/webcomponents/css'
                'js': 'media/system/webcomponents/js'
          'field-user':
                'css': 'media/system/webcomponents/css'
                'js': 'media/system/webcomponents/js'

## DO NOT EDIT THE FOLLOWING LINES UNLESS YOU KNOW WHAT YOU ARE DOING ##
CmAddons:
        js:
            - 'addon/display/fullscreen.js'
            - 'addon/display/panel.js'
            - 'addon/edit/closebrackets.js'
            - 'addon/edit/closetag.js'
            - 'addon/edit/matchbrackets.js'
            - 'addon/edit/matchtags.js'
            - 'addon/fold/brace-fold.js'
            - 'addon/fold/foldcode.js'
            - 'addon/fold/foldgutter.js'
            - 'addon/fold/xml-fold.js'
            - 'addon/mode/loadmode.js'
            - 'addon/mode/multiplex.js'
            - 'addon/scroll/simplescrollbars.js'
            - 'addon/selection/active-line.js'
            - 'keymap/vim.js'
            - 'mode/meta.js'
        css:
            - 'addon/display/fullscreen.css'
            - 'addon/fold/foldgutter.css'
            - 'addon/scroll/simplescrollbars.css'
